image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: CSEzDTZNttN+SosMFe2gbuoOzV1ek2RN4zM79Ne5Hab474Jo6pcKl0D/Mtyyc13SyapUZWgxaQsqN769vPwgAMr2c+pOd3xJt1thc1JwICaUKi0UpEyGVaG1rJdIeHVv

install:
- pip install -r requirements.txt

build_script:
- flet pack app_bar_test.py.py --name app_bar_test.py --icon icon.png --product-name app_bar_test.py --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a app_bar_test.py-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: app_bar_test.py-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf app_bar_test.py-macos.tar.gz -C dist app_bar_test.py.app

  artifacts:
  - path: app_bar_test.py-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf app_bar_test.py-linux.tar.gz -C dist app_bar_test.py

  artifacts:
  - path: app_bar_test.py-linux.tar.gz

